services:
  - type: web
    name: teller-clean-web
    env: node
    rootDir: teller_clean
    plan: free
    buildCommand: "npm ci || npm install"
    startCommand: "node server.js"
    autoDeploy: true
    envVars:
      - key: PORT
        value: "10000"
      - key: NODE_ENV
        value: "production"
      - key: DATABASE_URL
        fromDatabase:
          name: teller-clean-db
          property: connectionString
    healthCheckPath: /health

  - type: cron
    name: teller-clean-refresh
    schedule: "0 6 * * *"  # 6:00 UTC daily
    env: docker
    plan: standard
    startCommand: >
      bash -lc 'curl -fsS -X POST "$WEB_URL/admin/refresh" -H "X-Admin-Secret: $ADMIN_REFRESH_SECRET"'
    envVars:
      - key: WEB_URL           # set after first deploy to your web service URL
        sync: false
      - key: ADMIN_REFRESH_SECRET
        sync: false

databases:
  - name: teller-clean-db
    plan: free
